engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
      linebreak-style:
        enabled: false
      import/extensions:
        enabled: false
  fixme:
    enabled: true
ratings:
    paths:
      - "server/**/*.js"
languages:
  JavaScript: true
exclude_paths:
  - "node_modules/"
  - "client/*"
  - "client/public/*"
  - "template/*"
  - "server/routes"
  - "server/__test__"
  - "server/seeders/*"
  - "server/migrations/*"
  - "server/models/*"
  - "public/"
  - "e2eTest/*"
  - "e2ereports/*"
  - "coverage/*"
  - "server/config/*"
  - "server/controllers/recipes.js"