export default {
  REGISTER: 'REGISTER USER',
  LOGOUT: 'LOG OUT',
  LOGIN: 'LOGIN',
  AUTH_ERROR: 'AUTH ERROR',
  POST_RECIPE: 'POST RECIPE',
  HOME_RECIPE: 'HOME RECIPE',
  GET_ALL_RECIPES: 'GET ALL RECIPES',
  GET_SINGLE_RECIPE: 'GET SINGLE RECIPE',
  GET_USER_RECIPES: 'GET USER RECIPES',
  CLEAR_NEW_RECIPE: 'CLEAR NEW RECIPE',
  ADD_REVIEW: 'ADD REVIEW',
  GET_EDIT_RECIPE: 'GET EDIT RECIPE',
  EDIT_RECIPE: 'EDIT RECIPE',
  DELETE_RECIPE: 'DELETE RECIPE',
  ADD_FAVOURITE: 'ADD FAVOURITE',
  REMOVE_FAVOURITE: 'REMOVE FAVOURITE',
  GET_FAVOURITE: 'GET FAVOURITES',
  UPVOTE_RECIPE: 'UP VOTE RECIPE',
  REMOVE_UPVOTE: 'REMOVE UPVOTE',
  DOWNVOTE_RECIPE: 'DOWN VOTE RECIPE',
  REMOVE_DOWNVOTE: 'REMOVE DOWNVOTE',
  IS_LOADING: 'IS LOADING',
  STOP_LOADING: 'STOP LOADING'

};

